[theme]
primaryColor = '#F63366'
backgroundColor = '#FFFFFF'
secondaryBackgroundColor = '#F0F2F6'
textColor = '#262730'
font = 'sans serif'

[server]
enableCORS = false
headless = true

[browser]
gatherUsageStats = false  # This disables the "Made with Streamlit" footer
